# Climatic Water Balance Calculator Configuration

# Input data paths
input:
  temperature:
    path: "data/crespi.zarr"
    variable: "temperature"  # Variable name in zarr dataset
    units: "celsius"  # Expected units
  precipitation:
    path: "data/crespi.zarr"
    variable: "precipitation"  # Variable name in zarr dataset
    units: "mm"  # Expected units
  landuse:
    path: "data/landuse_250m.tif"
    crs: "EPSG:32632"
  kc_coefficients:
    path: "data/kc_values.xlsx"
    sheet_name: "marsoner"

# Output configuration
output:
  directory: "results"
  filename_pattern: "water_balance_{frequency}_{start_date}_{end_date}.tif"
  format: "GTiff"
  compression: "LZW"
  create_report: false  # Generate metadata and statistics report

# Spatial parameters
spatial:
  target_resolution: 250  # Output resolution in meters
  resampling_method: "bilinear"  # Method for resampling (nearest, bilinear, cubic)
  bounds:  # Optional bounds to limit calculation area (minx, miny, maxx, maxy)
    minx: 631928
    miny: 5161673
    maxx: 646735
    maxy: 5169860

# Temporal parameters
temporal:
  start_date: "1989-01-01"
  end_date: "1989-12-31"
  output_frequency: "monthly"  # Options: daily, monthly, seasonal, annual

# Processing options
processing:
  use_dask: false
  chunk_size:
    time: -1  # Number of time steps per chunk
    lon: 70  # Pixels in x direction per chunk
    lat: 70  # Pixels in y direction per chunk
  parallel_workers: 4  # Number of parallel workers for dask
  memory_limit: "4GB"  # Memory limit for dask
  cache_intermediates: true  # Cache intermediate results

# Calculation parameters
calculation:
  thornthwaite:
    # Latitude correction method
    latitude_correction: false #implement this
    daily_downscaling: false
  water_balance:
    # Soil parameters for water balance calculation
    include_soil_moisture: false  # If true, include soil moisture in calculation
    # soil_moisture_capacity: 100  # mm, only used if include_soil_moisture is true

# Seasonal Kc coefficient periods (for mapping seasonal values)
seasons:
  Kini: ["03", "04", "05"]
  Kmid: ["06", "07", "08"]
  Kend: ["09", "10"]
  Kcold: ["01", "02", "11", "12"]