# Climatic Water Balance Calculator Configuration

# Input data paths
input:
  temperature:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Daten/crespi.zarr" #"data/crespi.zarr"
    variable: "temperature"  # Variable name in zarr dataset
    units: "celsius"  # Expected units
  precipitation:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Daten/crespi.zarr" #"data/crespi.zarr"
    variable: "precipitation"  # Variable name in zarr dataset
    units: "mm"  # Expected units
  landuse:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/landuse_250m.tif"
  kc_coefficients:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/kc_values.xlsx"
    sheet_name: "marsoner"
  watersheds:
    root: C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/watersheds_validation #C:/OneDrive/Scientific Network South Tyrol/Wasserbilanz Südtirol - General/8_drought_indicators_water_group/sample_points/watersheds/raster
    pattern: "*.tif"
  stations:
    root: C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/AW_Durchflussmessreihen
    pattern: "*TagMittel.csv"
  station_distance:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/distance_stations_slope.tif"
  wind_effect:
    path: "C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/data/Wind Effect.tif"


# Output configuration
output:
  save_grids: false
  directory: C:/Users/tscho/OneDrive - Scientific Network South Tyrol/Projekte/Wasserbilanz Südtirol - v2/results
  filename_pattern: "water_balance_{frequency}_{start_date}_{end_date}.tif"
  format: "GTiff"
  compression: "LZW"
  create_report: false  # Generate metadata and statistics report

  # intermediate:
  #   temperature: 
  #     pattern: "data/temp/tair_{timestamp}.tiff"
  #     start_date: "1989-01-01"
  #     end_date: "1989-01-10"
  #   precipitation: 
  #     pattern: "data/temp/prec_{timestamp}.tiff"
  #     start_date: "1989-01-01"
  #     end_date: "1989-01-10"

# Spatial parameters
spatial:
  target_resolution: 250  # Output resolution in meters
  target_crs: "EPSG:32632"
  resampling_method: "bilinear"  # Method for resampling (nearest, bilinear, cubic)
  region: brixen

# Temporal parameters
temporal:
  start_date: "1999-10-01"
  end_date: "2000-09-30"
  output_frequency: [monthly, annual]  # Options: daily, monthly, seasonal, annual

# Processing options
processing:
  use_dask: false
  chunk_size: auto

# Calculation parameters
calculation:
  temperature:
    temperature_correction: true
    radiation_files: "C:/Users/tscho/Desktop/rad_corr.nc"
  precipitation:
    precipitation_correction: true
  thornthwaite:
    latitude_correction: true
    daily_downscaling: false #not implemented

# Seasonal Kc coefficient periods (for mapping seasonal values)
seasons:
  Kini: ["03", "04", "05"]
  Kmid: ["06", "07", "08"]
  Kend: ["09", "10"]
  Kcold: ["01", "02", "11", "12"]