# Climatic Water Balance Calculator Configuration

# Input data paths
input:
  temperature:
    path: "C:/OneDrive/OneDrive - Scientific Network South Tyrol/Codebase/Rechunk_Crespi_Files/data/crespi.zarr" #"data/crespi.zarr"
    variable: "temperature"  # Variable name in zarr dataset
    units: "celsius"  # Expected units
  precipitation:
    path: "C:/OneDrive/OneDrive - Scientific Network South Tyrol/Codebase/Rechunk_Crespi_Files/data/crespi.zarr" #"data/crespi.zarr"
    variable: "precipitation"  # Variable name in zarr dataset
    units: "mm"  # Expected units
  landuse:
    path: "data/landuse_250m.tif"
    crs: "EPSG:32632"
  kc_coefficients:
    path: "data/kc_values.xlsx"
    sheet_name: "marsoner"

# Output configuration
output:
  directory: "results"
  filename_pattern: "water_balance_{frequency}_{start_date}_{end_date}.tif"
  format: "GTiff"
  compression: "LZW"
  create_report: false  # Generate metadata and statistics report

  # intermediate:
  #   temperature: 
  #     pattern: "data/temp/tair_{timestamp}.tiff"
  #     start_date: "1989-01-01"
  #     end_date: "1989-01-10"
  #   precipitation: 
  #     pattern: "data/temp/prec_{timestamp}.tiff"
  #     start_date: "1989-01-01"
  #     end_date: "1989-01-10"

# Spatial parameters
spatial:
  target_resolution: 250  # Output resolution in meters
  resampling_method: "bilinear"  # Method for resampling (nearest, bilinear, cubic)
  region: WestGross

# Temporal parameters
temporal:
  start_date: "1989-01-01"
  end_date: "1989-12-31"
  output_frequency: [monthly, annual]  # Options: daily, monthly, seasonal, annual

# Processing options
processing:
  use_dask: true
  chunk_size: auto
  parallel_workers: 4  # Number of parallel workers for dask
  memory_limit: "4GB"  # Memory limit for dask
  cache_intermediates: true  # Cache intermediate results

# Calculation parameters
calculation:
  temperature:
    temperature_correction: true
    radiation_files: "C:/Users/tscho/Desktop/rad_corr.nc"
  precipitation:
    precipitation_correction: true
  thornthwaite:
    latitude_correction: true
    daily_downscaling: false #not implemented

# Seasonal Kc coefficient periods (for mapping seasonal values)
seasons:
  Kini: ["03", "04", "05"]
  Kmid: ["06", "07", "08"]
  Kend: ["09", "10"]
  Kcold: ["01", "02", "11", "12"]